/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: Machinegun weapon
 
 Comment: 

================================================================================
*/

class FDM_Machinegun : FDM_BaseWeapon replaces Chaingun
{
	Default
	{
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "Clip";
		Inventory.PickupMessage "$GOTMACHGUN";
		Obituary "$OB_MPCHAINGUN";
		Tag "$TAGMACHGUN";
		Decal "BulletChip";
	}
	States
	{
	Ready:
		MGUN A 1 A_WeaponReady;
		Loop;
	Deselect:
		MGUN A 1 A_DeselectionShit();
		"####" A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,49,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,60,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,80,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
	FinishDeselect:
		"####" A 0 A_Lower;
		Loop;
	Select:
		MGUN A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,80,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,60,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,49,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
		"####" A 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOFIRE);
		goto Ready;
	Fire:
		MGUN B 1 BRIGHT
		{
			A_PlaySound("weapons/machinegun/fire", CHAN_WEAPON);
			A_GunFlash();
			A_FireBullets(2, 2, 1, 7, "BulletPuff");
			A_ZoomFactor(0.997,ZOOM_INSTANT|ZOOM_NOSCALETURNING);
			A_QuadNoise();
		}
		MGUN C 1 BRIGHT A_ZoomFactor(0.998,ZOOM_NOSCALETURNING);
		MGUN D 1 A_ZoomFactor(1.0,ZOOM_NOSCALETURNING);
		MGUN B 1 BRIGHT
		{
			A_PlaySound("weapons/machinegun/fire", CHAN_WEAPON);
			A_GunFlash();
			A_FireBullets(3.5, 3.5, 1, 7, "BulletPuff");
			A_ZoomFactor(0.997,ZOOM_INSTANT|ZOOM_NOSCALETURNING);
			A_QuadNoise();
		}
		MGUN C 1 BRIGHT A_ZoomFactor(0.998,ZOOM_NOSCALETURNING);
		MGUN D 1 A_ZoomFactor(1.0,ZOOM_NOSCALETURNING);
		MGUN B 1 BRIGHT
		{
			A_PlaySound("weapons/machinegun/fire", CHAN_WEAPON);
			A_GunFlash();
			A_FireBullets(5.6, 5.6, 1, 7, "BulletPuff");
			A_ZoomFactor(0.997,ZOOM_INSTANT|ZOOM_NOSCALETURNING);
			A_QuadNoise();
		}
		MGUN C 1 BRIGHT A_ZoomFactor(0.998,ZOOM_NOSCALETURNING);
		MGUN D 1 A_ZoomFactor(1.0,ZOOM_NOSCALETURNING);
		MGUN A 8;
		CHGG B 0 A_ReFire;
		Goto Ready;
	Flash:
		TNT1 A 4 Bright A_Light1;
		Goto LightDone;
		TNT1 A 4 Bright A_Light2;
		Goto LightDone;
	Spawn:
		MGUN Z -1;
		Stop;
	}
}