/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie, JoeyTD
 
 Purpose: BFG9000 weapon
 
 Comment:

================================================================================
*/

class FDM_BFG9000 : DoomWeapon replaces BFG9000
{
	Default
	{
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 40;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		+WEAPON.NOAUTOFIRE;
		Inventory.PickupMessage "$GOTBFG9000";
		Tag "$TAG_BFG9000";
	}
	States
	{
	Ready:
		BFGG A 1 A_WeaponReady;
		Loop;
	Deselect:
		BFGG A 1 A_PlaySound("weapons/swap");
		"####" A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,49,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,60,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,80,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
	FinishDeselect:
		"####" A 0 A_Lower;
		Loop;
	Select:
		BFGG A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,80,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,60,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,49,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
		"####" A 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOFIRE);
		goto Ready;
	Fire:
		BFGG A 20 A_PlaySound("weapons/bfg/charge", CHAN_WEAPON);
		BFGG B 10 A_GunFlash;
		BFGG B 10 
		{
			A_FireBFG();
			A_PlaySound("weapons/bfg/fire", CHAN_WEAPON);
		}
		BFGG B 20 A_ReFire;
		Goto Ready;
	Flash:
		BFGF A 11 Bright A_Light1;
		BFGF B 6 Bright A_Light2;
		Goto LightDone;
	Spawn:
		BFUG A -1;
		Stop;
	}
}

// Projectile Junk taken from Vanilla as Fuck by JoeyTD!

class FDM_BFGBall : BFGBall replaces BFGBall
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 25;
		Damage 100;
		Projectile;
		+RANDOMIZE
		+NOTAUTOAIMED
		RenderStyle "Add";
		Alpha 0.75;
		Obituary "$OB_MPBFG_BOOM";
	}
	
	int user_ang;
		
	States
	{
	Spawn:
		BFC1 A 0;
		BFC1 A 0 A_PlaySound("weapons/bfg/loop", CHAN_6, 1.0, 1);
		BFC1 A 2 Bright
		{
			A_SpawnItemEx("FDM_BFGBlastTShot2",0,0,0,0,0,5,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPOINTERS);
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,90,6);
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,180,6);
			A_SpawnProjectile("FDM_BFGBlastTrail", 0, 0, 0);
			A_SpawnItemEx("FDM_BFGSpark", 0, 0, 0, 0, 0, 0, 0, 128);
		}
		BFC1 F 2 Bright
		{
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,270,6);
			A_SpawnItemEx("FDM_BFGBlastTShot", 0, 0, 0, 0, 0, 0, 0, 128);
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,360,6);
			A_SpawnProjectile("FDM_BFGBlastTrail", 0, 0, 0);
			A_SpawnItemEx("FDM_BFGSpark", 0, 0, 0, 0, 0, 0, 0, 128);
		}
		BFC1 B 2 Bright
		{
			A_SpawnItemEx("FDM_BFGBlastTShot2",0,0,0,0,0,5,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPOINTERS);
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,90,6);
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,180,6);
			A_SpawnProjectile("FDM_BFGBlastTrail", 0, 0, 0);
			A_SpawnItemEx("FDM_BFGSpark", 0, 0, 0, 0, 0, 0, 0, 128);
		}
		BFC1 E 2 Bright
		{
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,270,6);
			A_SpawnItemEx("FDM_BFGBlastTShot", 0, 0, 0, 0, 0, 0, 0, 128);
			A_SpawnProjectile("FDM_BFGBlastTLite",0,0,360,6);
			A_SpawnProjectile("FDM_BFGBlastTrail", 0, 0, 0);
			A_SpawnItemEx("FDM_BFGSpark", 0, 0, 0, 0, 0, 0, 0, 128);
		}
		loop;
	Death:
		BFE1 A 0 
		{
			A_Explode(200,256, !XF_HURTSOURCE);
			A_PlaySound("weapons/bfg/explode", CHAN_6);
		}
		BFE1 AB 8 Bright;
		BFE1 C 8 Bright; //A_BFGSpray;
		BFE1 DEF 8 Bright;
		Stop;
	}
}

class FDM_BFGSpark : Actor
{
	Default
	{
		Alpha 0.75;
		+DONTSPLASH
		+NoClip
		+FLOAT
	}
	
	States
	{
	Spawn:
		GSMK DEFGHI 3; 
		Stop;
	}
}

class FDM_BFGBlastTrail : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 0; //35
		Damage 0;
		Projectile;
		+RANDOMIZE;
		RenderStyle "Add";
		Alpha 0.75;
	}
	
	States
	{
	Spawn:
		EBLT ABC 3 bright A_BishopMissileWeave;
		goto Death;
	Death:
		EBLT DEF 4 bright A_FadeOut(0.25);
		loop;
	}
}

class FDM_BFGBlastTLite : Actor
{
   Default
   {
	   Radius 6;
	   Height 12;
	   Speed 32;
	   Damage 50;
	   PROJECTILE;
	   RenderStyle "Add";
	   Alpha 0.80;
	   DeathSound "weapons/devzap";
	   +THRUGHOST
	   +RIPPER
	   +FORCEXYBILLBOARD
   }
   
   States
   {
   Spawn:
      DLIT ABC 1 Bright;
      Loop;
   Death:
      DLIT DEFGHIJKLMNO 1 Bright;
      Stop;
   }
}

class FDM_BFGBlastTShot : Actor
{
	Default
	{
		Radius 12;
		Height 6;
		Speed 32;
		Damage 50;
		PROJECTILE;
		RenderStyle "Add";
		Alpha 0.80;
		+THRUGHOST
		+RIPPER
		-NOGRAVITY
		DeathSound "weapons/devexp";
	}
	States
	{
	Spawn:
		LFX1 ABC 1 Bright;
		TNT1 A 0 A_CheckFloor("Death");
		loop;
	Death:
		DLIT DEFGHIJKLMNO 1 Bright;
		Stop;
	}
}

class FDM_BFGBlastTShot2 : Actor
{
	Default
	{
	   Radius 12;
	   Height 6;
	   Speed 32;
	   Damage 50;
	   PROJECTILE;
	   RenderStyle "Add";
	   Alpha 0.80;
	   +THRUGHOST;
	   +RIPPER;
	   // -NOGRAVITY;
	   DeathSound "weapons/devexp";
	}

	States
	{
	Spawn:
		LFX2 ABC 1 Bright;
		TNT1 A 0 ThrustThing(angle*64/360, 0, 0, 0);
		TNT1 A 0 A_CheckCeiling("Death");
		loop;
   Death:
		DLIT DEFGHIJKLMNO 1 Bright;
		Stop;
	}
}