/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: Shotgun weapon
 
 Comment:

================================================================================
*/

class FDM_Shotgun : FDM_BaseWeapon replaces Shotgun
{
	Default
	{
		Weapon.SelectionOrder 1300;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.AmmoType "Shell";
		Inventory.PickupMessage "$GOTSHOTGUN";
		Obituary "$OB_MPSHOTGUN";
		Tag "$TAG_SHOTGUN";
		Decal "BulletChip";
	}
	States
	{
	Ready:
		STGN A 1 A_WeaponReady;
		Loop;
	Deselect:
		STGN A 1 A_DeselectionShit();
		"####" A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,49,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,60,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,80,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
	FinishDeselect:
		"####" A 0 A_Lower;
		Loop;
	Select:
		STGN A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,80,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,60,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,49,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		"####" A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
		"####" A 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOFIRE);
		goto Ready;
	Fire:
		STGN A 0;
		STGN B 2 BRIGHT Offset (0,40)
		{
			A_FireBullets (5.6, 0, 7, 5, "BulletPuff");
			A_PlaySound ("weapons/shotgun/fire", CHAN_WEAPON);
			A_GunFlash();
			A_ZoomFactor(0.96,ZOOM_INSTANT|ZOOM_NOSCALETURNING);
			A_QuadNoise();
		}
		STGN C 2 BRIGHT Offset (0,41) A_ZoomFactor(0.98,ZOOM_NOSCALETURNING);
		STGN B 2 BRIGHT Offset (0,39) A_ZoomFactor(0.99,ZOOM_NOSCALETURNING);
		STGN A 2 Offset (0,37) A_ZoomFactor(1.0,ZOOM_NOSCALETURNING);
		STGN A 2 Offset (0,35);
		STGN A 1 Offset (-5,32);
		STGN A 1 Offset (-10,32);
		STGN D 1 Offset (-20,32);
		STGN D 1 Offset (-35,32);
		STGN E 1 Offset (-42,32);
		STGN E 1 Offset (-46,32);
		STGN F 1 Offset (-48,32) A_PlaySound("weapons/shotgun/cock");
		STGN F 1 Offset (-52,32);
		STGN G 1 Offset (-56,32);
		STGN G 1 Offset (-58,32);
		STGN H 1 Offset (-59,32);
		STGN H 1 Offset (-60,32);
		STGN G 1 Offset (-58,32);
		STGN G 1 Offset (-56,32);
		STGN F 1 Offset (-52,32);
		STGN F 1 Offset (-48,32);
		STGN E 1 Offset (-46,32);
		STGN E 1 Offset (-42,32);
		STGN D 1 Offset (-25,32);
		STGN D 1 Offset (-20,32);
		STGN A 1 Offset (-10,32);
		STGN A 1 Offset (-5,32);
		STGN A 0 Offset (0,32);
		STGN A 0 A_ReFire;
		Goto Ready;
	Flash:
		TNT1 A 4 Bright A_Light1;
		TNT1 B 3 Bright A_Light2;
		Goto LightDone;
	Spawn:
		STGN Z -1;
		Stop;
	}
}