/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: Scripting actors
 
 Comment: 

================================================================================
*/
class FDM_PushyBastard32 : Actor
{
	Default
	{
		radius 32;
		height 64;
		+SOLID
		+NOGRAVITY
		//$Category "FauxDM Gameplay"
		//$Title "AI Actor Redirector - 32 Wide"
		//$IsDecoration
		//$Color 11
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (other is "FDM_BaseMonster" && other.health > 0 && !other.InStateSequence(CurState, ResolveState("Pain")))
		{
			other.angle = self.angle;
		}
		return false;
	}
}

class FDM_PushyBastard64 : FDM_PushyBastard32
{
	Default
	{
		radius 64;
		//$Category "FauxDM Gameplay"
		//$Title "AI Actor Redirector - 64 Wide"
		//$IsDecoration
		//$Color 11
	}
}

//$GZDB_SKIP
class FDM_SecActHitFloor : SectorAction replaces SecActHitFloor
{
	Default
	{
		Health SECSPAC_HitFloor;
	}
	
	override void BeginPlay ()
	{
		Super.BeginPlay ();

		// Make scripts that the player can trigger also get triggered
		// by monsters, for something approaching consistency.
		if (!bFRIENDLY && fdm_monsterscriptactors)
		{
			bAMBUSH = true;
		}
	}
}