/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: Powerups
 
 Comment: 

================================================================================
*/

class FDM_Berserk : CustomInventory replaces Berserk
{
	Default
	{
		+COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.ISHEALTH
		Inventory.PickupMessage "$GOTBERSERK";
		Inventory.PickupSound "items/powerups/berserk";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
	}
	States
	{
	Spawn:
		PSTR A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PowerStrength");
		TNT1 A 0 HealThing(100, 0);
		TNT1 A 0 A_SelectWeapon("FDM_Gauntlet");
		Stop;
	}
}

// Taken from MetaDoom because lazy.
class FDM_QuadDamage : PowerupGiver
{
	Default
	{
		+COUNTITEM
		+INVENTORY.AUTOACTIVATE
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.BIGPOWERUP
		+FLOATBOB
		Inventory.MaxAmount 0;
		powerup.type "PowerDamage";
		Powerup.Duration -30;
		damagefactor 4;
		Powerup.Color "AF 00 FF", 0.3;
		scale 0.75;
		RenderStyle "Translucent";
		Inventory.PickupMessage "$GOTQUAD";
		Inventory.PickupSound "items/powerups/quad";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Category "Powerups"
		//$Title "Quad Damage"
		//$NotAngled
		//$Color 9
	}
	
	States
	{
	Spawn:
		QUAD ABCDCB 6 Bright;
		Loop;
	}
}

// More MetaDoom rippery
class FDM_InvulnerabilitySphere : PowerupGiver replaces InvulnerabilitySphere
{
	Default
	{
		+COUNTITEM
		+INVENTORY.AUTOACTIVATE
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.BIGPOWERUP
		+FLOATBOB
		scale 0.75;
		Inventory.MaxAmount 0;
		powerup.type "PowerInvulnerable";
		Powerup.Color "GoldMap";
		Inventory.PickupMessage "$GOTINVUL";
		Inventory.PickupSound "items/powerups/invuln";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
	}
	
	States
	{
	Spawn:
		PINV ABCDCB 6 Bright;
		Loop;
	}
}

// Soulsphere
class FDM_Soulsphere : Health replaces Soulsphere
{
	Default
	{
		+COUNTITEM
		+INVENTORY.AUTOACTIVATE
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.FANCYPICKUPSOUND
		+FLOATBOB
		scale 0.75;
		Inventory.Amount 100;
		Inventory.MaxAmount 200;
		Inventory.PickupMessage "$GOTSUPER";
		Inventory.PickupSound "items/powerups/soulsphere";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
	}
	
	States
	{
	Spawn:
		SOUL ABCDCB 6 Bright;
		Loop;
	}
}

// Megasphere
class FDM_Megasphere : CustomInventory replaces Megasphere
{
	Default
	{
		+COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		+FLOATBOB
		scale 0.75;
		Inventory.PickupMessage "$GOTMSPHERE";
		Inventory.PickupSound "items/powerups/megasphere";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
	}
	
	States
	{
	Spawn:
		MEGA ABCD 6 BRIGHT;
		Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("FDM_BlueArmor", 1);
		TNT1 A 0 A_GiveInventory("MegasphereHealth", 1);
		Stop;
	}
}	

class FDM_HasteSphere : PowerupGiver replaces BlurSphere
{
	Default
	{
		+COUNTITEM
		+INVENTORY.AUTOACTIVATE
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.BIGPOWERUP
		+FLOATBOB
		Inventory.MaxAmount 0;
		powerup.type "PowerSpeed";
		Speed 1.5;
		scale 0.75;
		Powerup.Duration -30;
		RenderStyle "Translucent";
		Inventory.PickupMessage "$GOTHASTE";
		Inventory.PickupSound "items/powerups/haste";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Category "Powerups"
		//$Title "HasteSphere"
		//$NotAngled
		//$Color 9
	}
	
	States
	{
	Spawn:
		HAST ABCD 2 Bright;
		Loop;
	}
}

class FDM_ProtectSuitRad : PowerupGiver
{
	Default
	{
		Height 46;
		+INVENTORY.AUTOACTIVATE
		+INVENTORY.ALWAYSPICKUP
		Inventory.MaxAmount 0;
		Inventory.PickupMessage "$GOTSUIT";
		Powerup.Type "PowerIronFeet";
		Inventory.PickupSound "items/powerups/radsuit";
		scale 0.75;
		Powerup.Duration -30;
	}
	States
	{
	Spawn:
		SUIT A -1 Bright;
		Stop;
	}
}	

class PowerAsbestos : PowerProtection
{
	Default
	{
		DamageFactor "Flamer", 0.0;
	}
}

class FDM_ProtectSuitAsbestos : PowerupGiver
{
	Default
	{
	Inventory.PickupMessage "$GOTSUIT";
	Powerup.Type "PowerAsbestos";
	Powerup.Duration -30;
	Inventory.MaxAmount 0;
	+INVENTORY.AUTOACTIVATE
	}
	States
	{
	Spawn:
		SUIT A -1 Bright;
		Stop;
	}
}

class FDM_RadSuit : CustomInventory replaces RadSuit
{
	Default
	{
		Height 46;
		+INVENTORY.AUTOACTIVATE
		+INVENTORY.ALWAYSPICKUP
		Inventory.PickupMessage "$GOTSUIT";
		Inventory.PickupSound "items/powerups/radsuit";
		scale 0.75;
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
	}
	
	States
	{
	Spawn:
		SUIT A -1 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("FDM_ProtectSuitRad", 1);
		TNT1 A 0 A_GiveInventory("FDM_ProtectSuitAsbestos", 1);
		Stop;
	}
}	

// Time Pickup
class FDM_Timesphere : CustomInventory replaces Allmap
{
	Default
	{
		+COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		+FLOATBOB
		scale 0.75;
		Inventory.PickupMessage "$GOTTIMESPHERE";
		Inventory.PickupSound "items/powerups/timesphere";
		//$Category "Powerups"
		//$Title "TimeSphere"
		//$NotAngled
		//$Color 9
	}
	
	States
	{
	Spawn:
		TIME A 6 BRIGHT;
		Loop;
	Pickup:
		TNT1 A 0 ACS_NamedExecuteAlways ("FDM_TimeSphereEffects", 0, 0, 0, 0);
		Stop;
	}
}	