/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: Ammo pickup actors
 
 Comment: 

================================================================================
*/

// Bullets
class FDM_Clip : Clip replaces Clip
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIP";
		Inventory.Amount 10;
		inventory.pickupsound "items/ammo/clip1";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Clip"
	}
	States
	{
	Spawn:
		CLIP A -1;
		Stop;
	}
}

class FDM_ClipBox : Clip replaces ClipBox
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIPBOX";
		Inventory.Amount 50;
		inventory.pickupsound "items/ammo/clip2";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Clip Box"
	}
	States
	{
	Spawn:
		AMMO A -1;
		Stop;
	}
}

// Shells
class FDM_Shell : Shell replaces Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLS";
		Inventory.Amount 4;
		inventory.pickupsound "items/ammo/shell1";
		scale 0.75;
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Shell"
	}
	States
	{
	Spawn:
		SHEL A -1;
		Stop;
	}
}

class FDM_ShellBox : Shell replaces ShellBox
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLBOX";
		Inventory.Amount 20;
		inventory.pickupsound "items/ammo/shell2";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Shell Box"
	}
	States
	{
	Spawn:
		SBOX A -1;
		Stop;
	}
}

// Rockets
class FDM_RocketAmmo : RocketAmmo replaces RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKET";
		Inventory.Amount 1;
		inventory.pickupsound "items/ammo/rocket1";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Rocket"
	}
	States
	{
	Spawn:
		ROCK A -1;
		Stop;
	}
}

class FDM_RocketBox : RocketAmmo replaces RocketBox
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKBOX";
		Inventory.Amount 5;
		inventory.pickupsound "items/ammo/rocket2";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Rocket Box"
	}
	States
	{
	Spawn:
		BROK A -1;
		Stop;
	}
}

// Cells
class FDM_Cell : Cell replaces Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTCELL";
		Inventory.Amount 20;
		inventory.pickupsound "items/ammo/cell1";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Cell"
	}
	States
	{
	Spawn:
		CELL A -1;
		Stop;
	}
}

class FDM_CellPack : Cell replaces CellPack
{
	Default
	{
		Inventory.PickupMessage "$GOTCELLBOX";
		Inventory.Amount 100;
		inventory.pickupsound "items/ammo/cell2";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Cell Box"
	}
	States
	{
	Spawn:
		CELP A -1;
		Stop;
	}
}

// Universal Ammo
class FDM_UniversalAmmo : CustomInventory replaces Backpack
{
	Default
	{
		+INVENTORY.ALWAYSPICKUP
		Inventory.PickupMessage "$GOTUNIAMMO";
		inventory.pickupsound "items/ammo/uni";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Title "Universal Ammo"
	}
	States
	{
	Spawn:
		UNAM A -1;
		Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("Clip", 20);
		TNT1 A 0 A_GiveInventory("Shell", 8);
		TNT1 A 0 A_GiveInventory("RocketAmmo", 2);
		TNT1 A 0 A_GiveInventory("Cell", 40);
		TNT1 A 0 A_GiveInventory("FDM_Fuel", 50);
		Stop;
	}
}

// Fuel
class FDM_Fuel : Ammo
{
	Default
	{
		Inventory.Amount 25;
		Inventory.MaxAmount 300;
		Ammo.BackpackAmount 25;
		Ammo.BackpackMaxAmount 600;
		Inventory.PickupMessage "$GOTFUEL";
		Inventory.Icon "FUELA0";
		inventory.pickupsound "items/ammo/fuel";
		Inventory.PickupFlash "FDM_ItemRespawnMarker";
		//$Category "Ammunition"
		//$Title "Flamethrower Fuel"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
		Spawn:
			FUEL A -1;
			Stop;
	}
}