/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: LevelCompatibility adjustments
 
 Comment: Some levels need a little extra KY Jelly to fit this mod inside of 'em

================================================================================
*/

class FDM_LevelPostProc : LevelPostProcessor
{
	protected void Apply(Name checksum, String mapname)
	{
		bool mapworks;
		
		// Check for a player 1 spawn point.
		for (int i = 0; i < 65535; i ++)
		{
			if (GetThingEdNum(i) == 1)
			{
				mapworks = true;
				break;
			}
		}
		
		// If one doesn't exist, add one. Otherwise the game'll error out.
		if (mapworks == false)
		{
			AddThing(1, (0,0,0), 0, SKILLS_ALL, MODES_ALL);
			console.printf("FDM_Notice: No player 1 start! So one was added via script\nso the game doesn't error out. Slap your level designer around\nso they don't do this again, thanks!");
		}
		
		// Enable multi-player only items in single player.
		if (!multiplayer)
		{
			for (int i = 0; i < 65535; i ++)
			{
				if (GetThingFlags(i) != MTF_SINGLE)
				{
					SetThingFlags(i, MTF_SINGLE);
				}
			}			 
		}
		
	}
}

class FDM_LevelCompatibility : LevelCompatibility
{
	protected void Apply(Name checksum, String mapname)
	{
		/*
		// Old way of enabling multi-player only items in single player.
		// This mangles thing flags, a better solution needs to be found
		if (!multiplayer && fdm_mpweaps)
		{
			for (int i = 0; i < 65535; i ++)
			{
				SetThingFlags(i, 2016);
			}			 
		}
		*/
		
		// IWAD Map Tweaks
		switch (checksum)
		{			
			case 'none':
				return;
				
			case '058FB092EA1B70DA1E3CBF501C4A91A1': // Doom1 E1M8
			{
				// Disable Exit Teleporter-O-Death
				ClearLineSpecial(299);
				ClearLineSpecial(300);
				ClearLineSpecial(301);
				ClearLineSpecial(302);
				ClearLineSpecial(303);
				ClearLineSpecial(304);
				ClearLineSpecial(305);
				ClearLineSpecial(306);
				
				// Auto-Do The Exit Stairs
				ClearLineSpecial(233);
				OffsetSectorPlane(53, Sector.floor, 8);
				OffsetSectorPlane(54, Sector.floor, 16);
				OffsetSectorPlane(61, Sector.floor, 24);
				OffsetSectorPlane(62, Sector.floor, 32);
				OffsetSectorPlane(63, Sector.floor, 40);
				OffsetSectorPlane(64, Sector.floor, 48);
				OffsetSectorPlane(65, Sector.floor, 56);
				OffsetSectorPlane(55, Sector.floor, 64);
				OffsetSectorPlane(56, Sector.floor, 72);
				OffsetSectorPlane(57, Sector.floor, 80);
				OffsetSectorPlane(58, Sector.floor, 88);
				OffsetSectorPlane(59, Sector.floor, 96);
				OffsetSectorPlane(60, Sector.floor, 104);
				OffsetSectorPlane(67, Sector.floor, 112);
				
				// Place Something Fun on the Teleporter Exit Spot
				AddThing(2003, (448,5120,0), 0, SKILLS_ALL, MODES_ALL);
				
				// Open Baron Holes Automagically
				OffsetSectorPlane(45, Sector.ceiling, 86);
				OffsetSectorPlane(49, Sector.ceiling, 86);
			}
				
			case '291F24417FB3DD411339AE82EF9B3597': // Doom2 MAP07
			{
				// Auto-lower the start room walls to avoid grief
				OffsetSectorPlane(19, Sector.floor, -80);
				ClearLineSpecial(162);
				
				// Open up the BFG room
				OffsetSectorPlane(25, Sector.ceiling, 112);
				ClearLineSpecial(169);
				break;
			}
		}
	}
}