/*
================================================================================
 FauxDM ZScript Code
 
 Author: The Kinsie
 
 Purpose: Remove all pre-existing monsters and keys from each map.
 
 Comment: Most of this is now handled by an event handler in fdm_events.

================================================================================
*/

// Remove all normal monsters from pre-existing maps for compatibility purposes,
// triggering bossdeath scripts where appropriate

//$GZDB_SKIP

class FDM_Blank : Actor
{
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
	    Stop;
	}
}

class FDM_ActivateBossScripts : Actor
{
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
	    Stop;
	}
}

class FDM_BlankedFatso : FDM_ActivateBossScripts replaces Fatso{}
class FDM_BlankedBaronOfHell : FDM_ActivateBossScripts replaces BaronOfHell{}
class FDM_BlankedArachnotron : FDM_ActivateBossScripts replaces Arachnotron{}